### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by nhrones** [nexojs/nexo#1]
Rethink the name 'nexo' ...
When you search for it, it is a popular crypt-currency.  This means it will be hard to find your app in web or YouTube.
Otherwise looks great, keep up the good work.

**Comment by katywings** [comment]
@nhrones Thanks for your feedback! I'll keep this open for now, so we can collect ideas from the community. I am neutral regarding name changes. IMHO a great chance for a "no way to return" name change could be in a later 1.0 release, when the api surface and philosophy of the project have stabelized.

**Comment by nhrones** [comment]
Not a problem.  I'm a fan of Deno, and have the same issue there.  Seems there's a singer or group on YouTube named Deno, and Google searches for Deno bring some very odd results.
By the way; I like your work here ... clean and concise ... very consumable.
